### ISSUE TITLE
Instal error

### ISSUE THREAD

**Issue by AlexandreTexier** [anrt-type/ANRT-Baskervville#1]
can't instal, on Mac OS, the .otf files: 
- error in fontExplorer X pro (not allowed to instal)
- fatal error on mac font library (red cross)
- "could not be opend, no name table" on Glyphs

I have no idea what is the problem with those files...

**Comment by RosaWagner** [comment]
Thank you for these informations.

It works fine from here (Mac Mojave 10.14 and previous version, FontExplorer 6 and Mac Font Library). The checks indicated some warnings but nothing that disable the font. I updated the font files and added TTF, you can try again… 

Next days I will check with someone else and I'll let you know.

**Comment by AlexandreTexier** [comment]
ok merci, I'm downloading the full repo, just in case, to see if it works better. for now both the .ttf and .otf don't work like the old ones... bad magic

**Comment by AlexandreTexier** [comment]
OK by downloading the full repo it works now.. sorry for bothering
