### ISSUE TITLE
Google Fonts QA report

### ISSUE THREAD

**Issue by m4rc1e** [anrt-type/ANRT-Baskervville#3]
## Fontbakery report

Fontbakery version: 0.7.8

<details>
<summary><b>[2] Family checks</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Fonts have equal numbers of glyphs?</summary>

* [com.google.fonts/check/family/equal_numbers_of_glyphs](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/family/equal_numbers_of_glyphs)
* 🔥 **FAIL** Italic has 503 glyphs while Regular has 660 glyphs. There are 171 different glyphs among them: l.sc, period.sc, zacute.sc, aacute.sc, w.sc, t.sc, uni0146.sc, q.sc, uni0237.calt, braceleft.sc (and more)

</details>
<details>
<summary>🔥 <b>FAIL:</b> Fonts have equal glyph names?</summary>

* [com.google.fonts/check/family/equal_glyph_names](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/family/equal_glyph_names)
* 🔥 **FAIL** Glyphname 'braceleft.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni01D7.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'bracketright.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'gravecomb.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'igrave.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'quoteleft.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'idieresis.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'quotesingle.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'eacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni030C.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'k.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'edotaccent.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'v.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'h.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'i.sc.loclTRK' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'umacron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'lacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'tbar.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'abreve.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 's.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'cacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'wgrave.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'w.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0237.calt' is defined on Italic but is missing on Regular.
* 🔥 **FAIL** Glyphname 'uni013C.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'oacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'oslash.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'f_t.liga' is defined on Italic but is missing on Regular.
* 🔥 **FAIL** Glyphname 'uni0335.case.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'quotedblleft.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ccaron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'racute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ograve.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'edieresis.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'caroncomb.alt.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ycircumflex.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0338.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'eng.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0163.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'questiondown.case' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'emacron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'hbar.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni01CE.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'u.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'tildecomb.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni01D2.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'dcaron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'scaron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni01DB.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'eogonek.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni1EF9.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 't.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'q.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'braceright.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'oe.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0157.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'exclamdown.case' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ldot.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'q.calt' is defined on Italic but is missing on Regular.
* 🔥 **FAIL** Glyphname 'b.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'amacroan' is defined on Italic but is missing on Regular.
* 🔥 **FAIL** Glyphname 'parenright.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'wacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ocircumflex.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'bracketleft.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'acircumflex.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'udieresis.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'scedilla.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0219.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni030B.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'tcaron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'wdieresis.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ecircumflex.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'agrave.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'Aringacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'exclam.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'r.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0123.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ohungarumlaut.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'f.calt' is defined on Italic but is missing on Regular.
* 🔥 **FAIL** Glyphname 't_t.liga' is defined on Italic but is missing on Regular.
* 🔥 **FAIL** Glyphname 'uni01D9.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ucircumflex.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0137.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'iogonek.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'wcircumflex.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'amacron' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ntilde.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0307.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'zacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'period.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'adieresis.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'caron.alt' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uhungarumlaut.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'nacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uring.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'rcaron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ydieresis.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'e.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'f.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'x.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0336.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'omacron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'y.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'zcaron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'quotedblright.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'quoteright.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ecaron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0337.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni01D0.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0308.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni25C7' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0146.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'thorn.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'imacron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'i.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'cdotaccent.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'yacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'j.calt' is defined on Italic but is missing on Regular.
* 🔥 **FAIL** Glyphname 'odieresis.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'dcroat.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'a.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ccedilla.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'n.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'iacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'zdotaccent.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'quotedbl.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni021B.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'amacron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'aacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'acutecomb.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'otilde.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0328.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'utilde.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'parenleft.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni030A.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'question.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'm.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'lcaron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'g.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'aring.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uogonek.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'gdotaccent.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ncaron.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'c.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'icircumflex.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'caroncomb.alt' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ugrave.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'sacute.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0191.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'd.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'l.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ygrave.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0302.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0306.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'lslash.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'gbreve.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'o.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'ae.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'p.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'z.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'atilde.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'egrave.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni01D5.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'eth.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni030B.case' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni0304.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'j.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'uni01D4.sc' is defined on Regular but is missing on Italic.
* 🔥 **FAIL** Glyphname 'aogonek.sc' is defined on Regular but is missing on Italic.

</details>
<br>
</details>
<details>
<summary><b>[12] Baskervville-Italic.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Check glyph coverage.</summary>

* [com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage)
* 🔥 **FAIL** Missing required codepoints: 0x000D (CARRIAGE RETURN), 0x2074 (SUPERSCRIPT FOUR) and 0x2215 (DIVISION SLASH)

</details>
<details>
<summary>🔥 <b>FAIL:</b> License URL matches License text on name table?</summary>

* [com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url)
* 🔥 **FAIL** A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry. Currently accepted licenses are Apache: 'http://www.apache.org/licenses/LICENSE-2.0' or Open Font License: 'http://scripts.sil.org/OFL'
 For a small set of legacy families the Ubuntu Font License 'https://www.ubuntu.com/legal/terms-and-policies/font-licence' may be acceptable as well.
When in doubt, please choose OFL for new font projects. [code: no-license-found]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright (c) 2018 by ANRT. All rights reserved.'
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright (c) 2018 by ANRT. All rights reserved.'

</details>
<details>
<summary>🔥 <b>FAIL:</b> PPEM must be an integer on hinted fonts.</summary>

* [com.google.fonts/check/integer_ppem_if_hinted](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/integer_ppem_if_hinted)
* 🔥 **FAIL** This is a hinted font, so it must have bit 3 set on the flags of the head table, so that PPEM values will be rounded into and integer value.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Name table records must not have trailing spaces.</summary>

* [com.google.fonts/check/name/trailing_spaces](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/name/trailing_spaces)
* 🔥 **FAIL** Name table record with key = (1, 0, 0, 8) has trailing spaces that must be removed: 'ANRT '
* 🔥 **FAIL** Name table record with key = (3, 1, 1033, 8) has trailing spaces that must be removed: 'ANRT '

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
* ⚠ **WARN** OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

</details>
<details>
<summary>⚠ <b>WARN:</b> Font has old ttfautohint applied?</summary>

* [com.google.fonts/check/old_ttfautohint](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/old_ttfautohint)
* ⚠ **WARN** ttfautohint used in font = 1.8; installed = 1.8.3; Need to re-run with the newer version!

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations.

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: uni00B5	Contours detected: 0	Expected: 1
Glyph name: uni2126	Contours detected: 0	Expected: 1
Glyph name: daggerdbl	Contours detected: 2	Expected: 1 or 3
Glyph name: partialdiff	Contours detected: 0	Expected: 2
Glyph name: uni2206	Contours detected: 0	Expected: 2
Glyph name: product	Contours detected: 0	Expected: 1
Glyph name: summation	Contours detected: 0	Expected: 1
Glyph name: radical	Contours detected: 0	Expected: 1
Glyph name: integral	Contours detected: 0	Expected: 1
Glyph name: uni0394	Contours detected: 0	Expected: 2
Glyph name: uni03BC	Contours detected: 0	Expected: 1
Glyph name: pi	Contours detected: 0	Expected: 1
Glyph name: uni03A9	Contours detected: 0	Expected: 1

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
* ⚠ **WARN** This font lacks caret positioning values for these ligature glyphs:
	- f_f_j.liga
	- f_h.liga
	- fl
	- f_j.liga
	- f_f_l.liga
	- t_t.liga
	- f_f_b.liga
	- f_f_k.liga
	- f_f_h.liga

   [code: incomplete-caret-pos-data]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + b
	- b + f
	- f + h
	- h + f
	- f + i
	- i + f
	- f + j
	- j + f
	- f + k
	- k + f
	- f + l
	- l + b
	- h + i
	- i + j
	- j + k
	- k + l
	- l + t
	- t + t

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking Vertical Metric Linegaps.</summary>

* [com.google.fonts/check/linegaps](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/hhea.html#com.google.fonts/check/linegaps)
* ⚠ **WARN** OS/2 sTypoLineGap is not equal to 0. [code: OS/2]

</details>
<br>
</details>
<details>
<summary><b>[11] Baskervville-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Check glyph coverage.</summary>

* [com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage)
* 🔥 **FAIL** Missing required codepoints: 0x000D (CARRIAGE RETURN), 0x2074 (SUPERSCRIPT FOUR) and 0x2215 (DIVISION SLASH)

</details>
<details>
<summary>🔥 <b>FAIL:</b> License URL matches License text on name table?</summary>

* [com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url)
* 🔥 **FAIL** A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry. Currently accepted licenses are Apache: 'http://www.apache.org/licenses/LICENSE-2.0' or Open Font License: 'http://scripts.sil.org/OFL'
 For a small set of legacy families the Ubuntu Font License 'https://www.ubuntu.com/legal/terms-and-policies/font-licence' may be acceptable as well.
When in doubt, please choose OFL for new font projects. [code: no-license-found]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright (c) 2018 by ANRT. All rights reserved.'
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright (c) 2018 by ANRT. All rights reserved.'

</details>
<details>
<summary>🔥 <b>FAIL:</b> PPEM must be an integer on hinted fonts.</summary>

* [com.google.fonts/check/integer_ppem_if_hinted](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/integer_ppem_if_hinted)
* 🔥 **FAIL** This is a hinted font, so it must have bit 3 set on the flags of the head table, so that PPEM values will be rounded into and integer value.

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
* ⚠ **WARN** OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

</details>
<details>
<summary>⚠ <b>WARN:</b> Font has old ttfautohint applied?</summary>

* [com.google.fonts/check/old_ttfautohint](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/old_ttfautohint)
* ⚠ **WARN** ttfautohint used in font = 1.8; installed = 1.8.3; Need to re-run with the newer version!

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations.

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: uni00B5	Contours detected: 0	Expected: 1
Glyph name: uni2126	Contours detected: 0	Expected: 1
Glyph name: daggerdbl	Contours detected: 2	Expected: 1 or 3
Glyph name: partialdiff	Contours detected: 0	Expected: 2
Glyph name: uni2206	Contours detected: 0	Expected: 2
Glyph name: product	Contours detected: 0	Expected: 1
Glyph name: summation	Contours detected: 0	Expected: 1
Glyph name: radical	Contours detected: 0	Expected: 1
Glyph name: integral	Contours detected: 0	Expected: 1
Glyph name: uni0394	Contours detected: 0	Expected: 2
Glyph name: uni03BC	Contours detected: 0	Expected: 1
Glyph name: pi	Contours detected: 0	Expected: 1
Glyph name: uni03A9	Contours detected: 0	Expected: 1

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + b
	- b + f
	- f + h
	- h + f
	- f + i
	- i + f
	- f + j
	- j + f
	- f + k
	- k + f
	- f + l
	- l + b
	- h + i
	- i + j
	- j + k
	- k + l

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking Vertical Metric Linegaps.</summary>

* [com.google.fonts/check/linegaps](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/hhea.html#com.google.fonts/check/linegaps)
* ⚠ **WARN** OS/2 sTypoLineGap is not equal to 0. [code: OS/2]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 11 | 14 | 128 | 11 | 129 |
| 0% | 4% | 5% | 44% | 4% | 44% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**

## Diff images: [anrt_qa.zip](http://35.188.158.120/media/0717bd84-12ba-4a82-a6ef-4023f79982e1/anrt_qa.zip)

**Comment by RosaWagner** [comment]
thank you for this report. I will look into it in the next days
